// Installed executable, real WebView/Rust IPC/device/plugin paths; no mocks.
// Invoked explicitly, never by the installer. Keeps/restores user preferences.
import {chromium} from 'playwright-core';
import {spawn} from 'node:child_process';
import {readFile,writeFile,mkdir,unlink} from 'node:fs/promises';
import {resolve,join,basename} from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {once} from 'node:events';
import assert from 'node:assert/strict';
const exe=resolve(process.argv[2]),out=resolve('output/package-validation'),work=join(out,randomUUID());await mkdir(work,{recursive:true});
const config=join(process.env.APPDATA,'local.minidaw.desktop');const backups=new Map();
for(const n of ['audio-preferences.json','recent-projects.json','plugin-catalog.json']){try{backups.set(n,await readFile(join(config,n)));}catch{backups.set(n,null);}}
const report={executable:basename(exe),sha256:createHash('sha256').update(await readFile(exe)).digest('hex'),checks:[],backends:[],exports:[],limitations:['Device callback/PCM submission verified; no acoustic listening or clean Windows VM.']};
let child,browser,page,local;const errors=[],sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label,ms=30000){const at=Date.now();while(Date.now()-at<ms){if(await fn())return;await sleep(70);}throw Error(label);}
const invoke=(name,args={})=>page.evaluate(({name,args})=>window.__TAURI_INTERNALS__.invoke(name,args).catch(e=>{throw Error(JSON.stringify(e));}),{name,args});
const project=()=>invoke('project_snapshot'),audio=()=>invoke('engine_snapshot');
async function idle(){await until(async()=>!await page.locator('#project-save').isDisabled(),'project idle');await sleep(100);}
async function edit(request){await idle();await invoke('edit_project',{revision:(await project()).revision,request});await idle();}
async function start(){child=spawn(exe,[],{cwd:work,env:{...process.env,PATH:join(process.env.SystemRoot,'System32')+';'+process.env.SystemRoot,CPAL_ASIO_DIR:'',LIBCLANG_PATH:'',WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:'--remote-debugging-port=19287'},stdio:'ignore',windowsHide:true});await until(async()=>{try{browser=await chromium.connectOverCDP('http://127.0.0.1:19287');return true;}catch{return false;}},'installed app start');await until(async()=>{page=browser.contexts()[0].pages().find(p=>p.url().includes('tauri.localhost')&&!p.url().includes('?'));return !!page;},'installed WebView');page.on('pageerror',e=>errors.push(e.message));await idle();}
async function quit(){if(browser)await browser.close();if(child?.exitCode===null){const done=once(child,'exit');child.kill();await done;}page=null;browser=null;}
async function playCheck(label){await invoke('transport_command',{action:'play'});await sleep(1600);const a=await audio();await sleep(3000);const b=await audio();const n=b.metrics.callbacks-a.metrics.callbacks;const r={label,backend:b.output?.backend,device:b.output?.device,rate:b.output?.sampleRate,callbacks:n,callbackAvgMs:(b.metrics.callbackAvgMs*b.metrics.callbacks-a.metrics.callbackAvgMs*a.metrics.callbacks)/n,overruns:b.metrics.overruns-a.metrics.overruns,deviceOverruns:b.metrics.deviceCallbackOverruns-a.metrics.deviceCallbackOverruns,starvation:b.source.starvation-a.source.starvation,streamErrors:b.streamErrors-a.streamErrors,peakDb:b.master.peakDb};report.backends.push(r);assert.ok(n>50);assert.equal(r.overruns,0);assert.equal(r.starvation,0);assert.equal(r.streamErrors,0);assert.equal(r.deviceOverruns,0);assert.ok(r.peakDb.some(x=>x>-90));await invoke('transport_command',{action:'stop'});}
try{
 await start();local=await page.evaluate(()=>Object.fromEntries(Object.entries(localStorage)));report.checks.push('Installed x64 program starts with System32-only PATH and no SDK/libclang environment.');
 let state=await audio();await invoke('apply_audio_settings',{settings:{...state.preferences,driverType:'wasapi',outputDevice:null}});await invoke('new_project',{revision:(await project()).revision,discard:true});await idle();
 for(const ext of ['wav','mp3','flac']){await invoke('load_audio',{path:resolve('tests/fixtures/stereo-44100.'+ext),trackId:null});await idle();}
 const at=(await project()).document.tracks[0].trackId;await edit({command:'track.mix',trackIds:[at],volumeDb:-20,pan:-.2});
 await edit({command:'midi.track.add'});const mt=(await project()).document.tracks.at(-1).trackId;await edit({command:'midi.track.instrument',trackIds:[mt],instrument:'basicSynth'});await edit({command:'midi.clip.add',trackIds:[mt],targetTick:'0',lengthTick:'15360000'});const mc=(await project()).document.tracks.at(-1).clips[0].clipId;await edit({command:'midi.note.add',clipIds:[mc],targetTick:'12345',lengthTick:'12000000',pitch:60,velocity:70});await edit({command:'track.mix',trackIds:[mt],volumeDb:-24,pan:.2});await edit({command:'project.cycle',cycle:{enabled:true,startTick:'0',endTick:'9600000'}});
 await playCheck('WASAPI Audio WAV/MP3/FLAC + internal MIDI Synth');
 report.checks.push('WAV/MP3/FLAC decode, Audio+MIDI Synth playback, Mixer gain/pan and Cycle on installed WASAPI.');
 const devices=await invoke('output_devices',{driverType:'asio'});const topping=devices.find(x=>/topping/i.test(x));assert.ok(topping,'TOPPING ASIO device missing');state=await audio();await invoke('apply_audio_settings',{settings:{...state.preferences,driverType:'asio',outputDevice:topping}});await playCheck('TOPPING ASIO Audio + Synth');
 const catalog=await invoke('plugin_scan',{paths:[resolve('tests/local/plugins/surge-xt-1.3.4')]});report.plugins=catalog.plugins.filter(p=>p.name.startsWith('Surge XT')).map(p=>({name:p.name,format:p.format,instrument:p.instrument}));assert.equal(report.plugins.length,4);
 for(const format of ['vst3','clap']){const d=catalog.plugins.find(p=>p.name==='Surge XT'&&p.format===format&&p.instrument);const plugin=await invoke('plugin_prepare',{descriptor:d});await edit({command:'midi.track.add'});const tid=(await project()).document.tracks.at(-1).trackId;await edit({command:'plugin.instrument',trackIds:[tid],plugin});await edit({command:'midi.clip.add',trackIds:[tid],targetTick:'0',lengthTick:'15360000'});const cid=(await project()).document.tracks.at(-1).clips[0].clipId;await edit({command:'midi.note.add',clipIds:[cid],targetTick:'12345',lengthTick:'12000000',pitch:format==='clap'?67:64,velocity:70});await edit({command:'track.mix',trackIds:[tid],volumeDb:-24,pan:0});const fx=catalog.plugins.find(p=>p.name==='Surge XT Effects'&&p.format===format);const insert=await invoke('plugin_prepare',{descriptor:fx});await edit({command:'effect.add',trackIds:format==='clap'?[]:[at],plugin:insert});}
 await playCheck('TOPPING ASIO + actual VST3/CLAP Instruments and Effects');
 const statuses=await invoke('plugin_status');assert.equal(statuses.length,4);assert.ok(statuses.every(s=>!s.error&&!s.info.faulted&&s.info.processCalls>0));
 for(const s of statuses){await invoke('plugin_editor',{instanceId:s.instanceId,show:true});await sleep(250);assert.equal((await invoke('plugin_status')).find(x=>x.instanceId===s.instanceId).info.editorOpen,true);await invoke('plugin_editor',{instanceId:s.instanceId,show:false});}
 report.checks.push('Four real Surge XT 1.3.4 VST3/CLAP instrument/effect instances process and native editors open/close.');
 await page.locator('#show-spectrum').click();await invoke('spectrum_configure',{settings:{enabled:true,fftSize:4096,smoothingMs:200},sources:[]});await invoke('transport_command',{action:'play'});await until(async()=>!!(await invoke('spectrum_snapshot',{after:0})).frame,'live spectrum');report.spectrum=await invoke('spectrum_snapshot',{after:0});delete report.spectrum.frame;delete report.spectrum.comparison;await sleep(500);await page.screenshot({path:join(out,'installed-spectrum.png')});await invoke('transport_command',{action:'stop'});
 await page.locator('#show-mixer').click();await sleep(250);await page.screenshot({path:join(out,'installed-mixer.png')});
 const saved=join(work,'installed.minidaw');await idle();await invoke('save_project',{path:saved,revision:(await project()).revision});await idle();const doc=(await project()).document;await quit();await start();await invoke('open_project',{path:saved,revision:(await project()).revision,discard:true});await idle();const restored=(await project()).document;assert.deepEqual(restored.tracks.map(t=>({id:t.trackId,name:t.name,kind:t.kind,clips:t.clips,mix:t.mix})),doc.tracks.map(t=>({id:t.trackId,name:t.name,kind:t.kind,clips:t.clips,mix:t.mix})));assert.equal((await invoke('plugin_status')).length,4);
 report.checks.push('Spectrum live frames and Mixer UI render; project, exact notes and plugin instances restore after a complete installed-app restart.');
 const sr=(await audio()).output.sampleRate;const tracks=restored.tracks.map(t=>t.trackId);
 for(const [mode,format]of [['mixdown','pcm16'],['selection','pcm24'],['track','float32'],['stems','float32']]){const r=await invoke('export_audio',{request:{jobId:randomUUID(),revision:(await project()).revision,path:mode==='stems'?work:join(work,mode+'.wav'),format,sampleRate:sr,overwrite:false,mode,trackIds:mode==='track'?[at]:mode==='stems'?tracks:[],range:mode==='mixdown'?null:{start:'123',end:String(sr*2+123)}}});assert.ok(r.frames>0&&r.files.length>0);if(mode!=='mixdown')assert.equal(r.frames,sr*2);if(mode==='stems')assert.equal(r.files.length,tracks.length);for(const f of r.files){const b=await readFile(f.path);assert.equal(b.toString('ascii',0,4),'RIFF');assert.equal(b.readUInt16LE(34),format==='pcm16'?16:format==='pcm24'?24:32);}report.exports.push({mode,format,frames:r.frames,files:r.files.length,realtimeFactor:r.realtimeFactor,peak:r.peak});}
 await page.locator('#play-pause').click();await until(async()=>(await audio()).transport.state==='playing','Play UI');await page.locator('#play-pause').click();await until(async()=>(await audio()).transport.state==='paused','Pause UI');await invoke('transport_command',{action:'stop'});report.checks.push('Installed Mixdown/Selection/Track/Stem exports, three WAV formats and exact range sample length; real Play/Pause UI buttons.');assert.deepEqual(errors,[]);report.passed=true;
}catch(e){report.error=String(e.stack??e);process.exitCode=1;if(page){report.audio=await audio().catch(()=>null);await page.screenshot({path:join(out,'installed-failure.png')}).catch(()=>{});}}
finally{if(page&&local)await page.evaluate(p=>{localStorage.clear();for(const[k,v]of Object.entries(p))localStorage.setItem(k,v);},local).catch(()=>{});await quit();for(const[n,bytes]of backups){if(bytes)await writeFile(join(config,n),bytes);else await unlink(join(config,n)).catch(()=>{});}report.pageErrors=errors;await writeFile(join(out,'installed-smoke.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,error:report.error,checks:report.checks,backends:report.backends,exports:report.exports},null,2));}
