// Actual release app. Only OS picker answers are supplied; project/audio IPC is real.
import {chromium} from 'playwright-core';import {spawn} from 'node:child_process';import {once} from 'node:events';import {readFile,writeFile,mkdir,unlink} from 'node:fs/promises';import {createHash,randomUUID} from 'node:crypto';import {resolve,join} from 'node:path';import assert from 'node:assert/strict';
const exe=resolve('src-tauri/target/release/minidaw.exe'),folder=resolve('tests/local/editing-ui',randomUUID());await mkdir(folder,{recursive:true});
const report={executableSha256:createHash('sha256').update(await readFile(exe)).digest('hex'),folder,checks:[],commits:[],backends:[]};const recentPath=join(process.env.APPDATA,'local.minidaw.desktop/recent-projects.json');let recentBefore;try{recentBefore=await readFile(recentPath);}catch{}
let child,browser,page,preferences;const errors=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const invoke=(name,args={})=>page.evaluate(({name,args})=>window.__TAURI_INTERNALS__.invoke(name,args),{name,args});const project=()=>invoke('project_snapshot'),snapshot=()=>invoke('engine_snapshot');
async function until(fn,message,timeout=20000){const t=performance.now();while(performance.now()-t<timeout){if(await fn())return;await sleep(25);}throw Error(message);}
async function launch(){child=spawn(exe,[],{env:{...process.env,WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:'--remote-debugging-port=19233'},stdio:'ignore',windowsHide:true});await until(async()=>{try{browser=await chromium.connectOverCDP('http://127.0.0.1:19233');return true;}catch{return false;}},'CDP');await until(async()=>{page=browser.contexts()[0].pages().find(p=>p.url().includes('tauri.localhost'));return Boolean(page);},'page');await page.setViewportSize({width:1440,height:1000});page.on('pageerror',e=>errors.push(e.message));await until(async()=>!(await page.locator('#project-save').isDisabled()),'Initialize');
 await page.evaluate(()=>{window.__answers=[];window.__calls={};const original=window.fetch;window.fetch=function(url,options){const cmd=decodeURIComponent(String(url)).split('/').at(-1);window.__calls[cmd]=(window.__calls[cmd]??0)+1;if(cmd==='plugin:dialog|open'||cmd==='plugin:dialog|save'){if(!window.__answers.length)throw Error('Missing picker response');return Promise.resolve(new Response(JSON.stringify(window.__answers.shift()),{status:200,headers:{'Content-Type':'application/json','Tauri-Response':'ok'}}));}return original.call(this,url,options);};});}
async function close(){if(browser){await browser.close();browser=null;}if(child?.exitCode===null){const e=once(child,'exit');child.kill();await e;}page=null;}
async function idle(){await until(async()=>!(await page.locator('#project-save').isDisabled()),'Edit completion');await sleep(50);}
async function answer(path){await page.evaluate(p=>window.__answers.push(p),path);}
async function menu(id){if(await page.locator('#file-menu').getAttribute('open')===null)await page.locator('#file-menu summary').click();await page.locator('#'+id).click();}
async function fresh(path='tests/fixtures/stereo-44100.wav'){await menu('project-new');if((await project()).dirty)await page.locator('#project-confirm-discard').click();await idle();await answer(resolve(path));await page.locator('#open-file').click();await idle();await until(async()=>(await snapshot()).waveform?.complete,'Waveform',120000);await until(async()=>await page.locator('.audio-clip').count()>0,'Clip UI');await sleep(150);}
async function key(k){await page.keyboard.press(k);await idle();}
async function select(id,ctrl=false){const node=page.locator(`[data-clip-id="${id}"]`);await node.scrollIntoViewIfNeeded();const b=await node.boundingBox();if(ctrl)await page.keyboard.down('Control');await page.mouse.click(b.x+Math.min(45,b.width*.4),b.y+Math.min(65,b.height*.5));if(ctrl)await page.keyboard.up('Control');}
async function tool(n){await page.locator('#edit-tools button').nth(n-1).click();}
async function ruler(seconds,moves=0){const b=await page.locator('#waveform').boundingBox();const scroll=Number(await page.locator('#scroll').inputValue());const max=Number(await page.locator('#scroll').getAttribute('max'));const zoom=Number((await page.locator('#zoom-value').textContent()).replace('×',''));const extent=max?max/(1-1/zoom):Math.max(10,(await snapshot()).duration*1.25);const span=extent/zoom;const x=b.x+(seconds-scroll)/span*b.width;const before=await snapshot();
 const trace=async()=>page.evaluate(()=>({aria:document.getElementById('waveform').getAttribute('aria-disabled'),dragging:document.getElementById('waveform').className,calls:{...window.__calls},events:window.__rulerEvents}));
 await page.evaluate(()=>{window.__rulerEvents=[];for(const type of ['pointerdown','pointerup','lostpointercapture','pointercancel','blur'])window.addEventListener(type,e=>{window.__rulerEvents.push({type,target:e.target.id,x:e.clientX,y:e.clientY,dragging:document.getElementById('waveform').className});},true);});
 report.ruler={before,box:b,x,trace:[]};await page.mouse.move(x,b.y+b.height*.75);report.ruler.trace.push(await trace());await page.mouse.down();report.ruler.trace.push(await trace());if(moves)await page.mouse.move(x+2,b.y+b.height*.75,{steps:moves});report.ruler.trace.push(await trace());assert.equal((await snapshot()).transport.appliedCommand,before.transport.appliedCommand);await page.mouse.up();report.ruler.trace.push(await trace());await until(async()=>(await snapshot()).transport.appliedCommand===before.transport.appliedCommand+1,'ruler seek');}
async function editMouse(id,handle,delta){const node=page.locator(`[data-clip-id="${id}"]`);await node.scrollIntoViewIfNeeded();const target=handle?node.locator(`[data-handle="${handle}"]`):node;const b=await target.boundingBox();const x=handle?b.x+b.width/2:b.x+Math.min(50,b.width/2),y=handle?b.y+b.height*.65:b.y+Math.min(70,b.height*.6);const p=await project(),s=await snapshot();const calls=await page.evaluate(()=>({...window.__calls}));await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+delta,y,{steps:100});assert.equal((await project()).revision,p.revision);assert.equal((await snapshot()).transport.appliedCommand,s.transport.appliedCommand);assert.equal((await page.evaluate(()=>window.__calls.edit_project??0)),calls.edit_project??0);await page.mouse.up();await idle();const after=await project();assert.equal(after.history.undo,p.history.undo+1);assert.equal(after.revision,p.revision+1);assert.equal((await snapshot()).analysisBuilds,s.analysisBuilds);report.commits.push(after.editMetrics);return after;}
async function save(path){if(path)await answer(path);await menu('project-save');await idle();assert.equal((await project()).dirty,false);}
const clips=p=>p.document.tracks.flatMap(t=>t.clips);
const sourcePaths=['wav','mp3','flac'].map(x=>resolve(`tests/fixtures/stereo-44100.${x}`));
const hashes=async()=>Promise.all(sourcePaths.map(async p=>({path:p,sha256:createHash('sha256').update(await readFile(p)).digest('hex')})));
try{
 report.sourcesBefore=await hashes();
 await launch();preferences=(await snapshot()).preferences;await invoke('apply_audio_settings',{settings:{...preferences,driverType:'wasapi',outputDevice:null,transportDeclick:true}});await fresh();let p=await project();const original=p.document;
 await tool(3);let b=await page.locator('.audio-clip').boundingBox();await page.mouse.click(b.x+b.width*.4,b.y+70);await idle();assert.equal(clips(await project()).length,2);await key('Control+z');assert.deepEqual((await project()).document,original);
 await tool(1);await select(clips(await project())[0].clipId);await ruler(2,100);await key('Alt+x');p=await project();assert.equal(clips(p).length,2);assert.equal(clips(p)[0].sourceEnd,clips(p)[1].sourceStart);
 await tool(2);b=await page.locator('#waveform').boundingBox();const before=await project();await page.mouse.move(b.x+b.width*.1,b.y+100);await page.mouse.down();await page.mouse.move(b.x+b.width*.3,b.y+100,{steps:100});await page.mouse.up();assert.equal((await project()).revision,before.revision);await key('Shift+x');assert.equal(clips(await project()).length,4);await key('Delete');assert.equal(clips(await project()).length,2);await key('Control+z');assert.equal(clips(await project()).length,4);
 report.checks.push('Tools 1/2/3, Split click, Alt+X, Shift+X, range Delete/Undo; ruler 100 moves=0 seek, up=1; exact source adjacency.');
 await fresh();await tool(1);for(const [n,name]of [[2,'rangeSelection'],[3,'split'],[1,'objectSelection']]){await key(String(n));assert.equal(await page.locator('#clip-layer').getAttribute('data-tool'),name);}p=await project();let id=clips(p)[0].clipId;await select(id);
 const cancelBox=await page.locator('.audio-clip').boundingBox(),cancelBefore=await project();await page.mouse.move(cancelBox.x+60,cancelBox.y+70);await page.mouse.down();await page.mouse.move(cancelBox.x+100,cancelBox.y+70,{steps:20});await page.locator('#clip-layer').evaluate(el=>el.dispatchEvent(new PointerEvent('pointercancel')));await page.mouse.up();assert.equal((await project()).revision,cancelBefore.revision);assert.equal(await page.locator('.audio-clip').evaluate(el=>el.style.transform),'');
 await key('Control+y');await key('Control+e');assert.equal((await project()).revision,cancelBefore.revision);
 await editMouse(id,'trim-left',30);await editMouse(id,'trim-right',-30);const trimmed=clips(await project())[0];assert.ok(Number(trimmed.sourceStart)>0);assert.ok(Number(trimmed.sourceEnd)<264600);await editMouse(id,null,40);assert.equal(clips(await project())[0].sourceStart,trimmed.sourceStart);await editMouse(id,'fade-in',40);await editMouse(id,'fade-out',-40);assert.ok(Number(clips(await project())[0].fadeIn.sourceFrames)>0);
 await select(id);await key('Shift+m');assert.equal(clips(await project())[0].mute,true);await key('Shift+u');assert.equal(clips(await project())[0].mute,false);await page.locator('#clip-gain').fill('-6');await page.locator('#clip-gain').press('Tab');await idle();assert.ok(Math.abs(clips(await project())[0].gain-10**(-6/20))<1e-12);
 await select(id);await key('Control+c');assert.equal((await project()).clipboardCount,1);await ruler(5);await key('Control+v');assert.equal(clips(await project()).length,2);await key('Control+d');assert.equal(clips(await project()).length,3);await key('Control+x');assert.equal(clips(await project()).length,2);await key('Control+v');assert.equal(clips(await project()).length,3);await key('Backspace');assert.equal(clips(await project()).length,2);
 report.checks.push('Actual 100-move Trim/Move/Fade drags: no intermediate mutations/commands, one transaction+undo each, no asset analysis rebuild; Mute/Unmute/Gain/Cut/Copy/Paste/Duplicate/Delete.');
 await fresh();await tool(1);id=clips(await project())[0].clipId;await select(id);await ruler(3);await key('Alt+x');p=await project();const splitIds=clips(p).map(c=>c.clipId);await select(splitIds[0]);await select(splitIds[1],true);await key('x');p=await project();assert.ok(clips(p).some(c=>Number(c.fadeOut.sourceFrames)>0));assert.ok(clips(p).some(c=>Number(c.fadeIn.sourceFrames)>0));
 await page.locator('.file-menu summary').filter({hasText:'오디오'}).click();await page.locator('#audio-menu-items [data-command="audio.normalize"]').click();await page.locator('#normalize-target').fill('-1');await page.locator('#normalize-apply').click();await idle();assert.ok(clips(await project()).every(c=>c.gain>1));
 const edited=(await project()).document;const path=join(folder,'편집 결과.minidaw');await save(path);await select(clips(await project())[0].clipId);await key('Shift+m');assert.equal((await project()).dirty,true);await key('Control+z');assert.equal((await project()).dirty,false);await key('Control+Shift+z');assert.equal((await project()).dirty,true);await key('Control+z');
 const count=(await project()).history.undo;for(let n=0;n<count-1;n++)await key('Control+z');assert.equal(clips(await project()).length,1);assert.equal(clips(await project())[0].gain,1);for(let n=0;n<count-1;n++)await key('Control+Shift+z');assert.deepEqual((await project()).document,{...edited,name:'편집 결과'});assert.equal((await project()).dirty,false);
 const savedBefore=await project();const exited=once(child,'exit');await menu('project-close');await exited;await close();await launch();await answer(path);await menu('project-open');await idle();assert.deepEqual((await project()).document,savedBefore.document);await until(async()=>await page.locator('.audio-clip').count()===2,'Restored UI');
 await page.screenshot({path:'docs/validation/editing-desktop.png'});report.savedProject=path;report.document=savedBefore.document;
 report.checks.push('X Crossfade + Peak Normalize; Undo/Redo exact state; saved-state dirty/clean; real Save/Exit/Relaunch/Open restores all Clip IDs and edits.');
 for(const backend of (process.argv.includes('--wasapi-only')?['wasapi']:['wasapi','asio'])){const settings={...(await snapshot()).preferences,driverType:backend,transportDeclick:true};if(backend==='asio')settings.asioDriver=(await invoke('output_devices',{driverType:'asio'}))[0];await invoke('apply_audio_settings',{settings});await invoke('transport_command',{action:'play'});await sleep(200);const before=await snapshot();for(let n=0;n<8;n++){p=await project();await invoke('edit_project',{revision:p.revision,request:{command:'audio.gain',clipIds:[clips(p)[0].clipId],gainDb:n%2?-1:-2}});}const after=await snapshot();assert.equal(after.transport.state,'playing');assert.ok(after.position>before.position);assert.equal(after.analysisBuilds,before.analysisBuilds);assert.equal(after.metrics.overruns,0);assert.equal(after.metrics.deviceCallbackOverruns,0);assert.equal(after.streamErrors,0);assert.equal(after.source.starvation,0);report.backends.push({backend,before,after});await invoke('transport_command',{action:'stop'});}
 report.checks.push('Edited timeline on every requested backend, eight edits while playing each: position advances, no overrun/starvation/stream error or peak rebuild.');
 report.sourcesAfter=await hashes();assert.deepEqual(report.sourcesAfter,report.sourcesBefore);assert.deepEqual(errors,[]);report.passed=true;
}catch(e){report.error=String(e.stack??e);if(page){await page.screenshot({path:'docs/validation/editing-failure.png'}).catch(()=>{});report.lastProject=await project().catch(()=>null);report.lastSnapshot=await snapshot().catch(()=>null);}process.exitCode=1;}
finally{if(page&&preferences)await invoke('apply_audio_settings',{settings:preferences}).catch(()=>{});await close();if(recentBefore)await writeFile(recentPath,recentBefore);else await unlink(recentPath).catch(()=>{});await writeFile('docs/validation/editing-ui.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,error:report.error,checks:report.checks,commits:report.commits}));}
