// Owned release WebView, real mouse edits and TOPPING ASIO sample-clock output.
import {chromium} from 'playwright-core';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {readFile,writeFile,mkdir,unlink,readdir} from 'node:fs/promises';
import {randomUUID,createHash} from 'node:crypto';
import {resolve,join} from 'node:path';
import assert from 'node:assert/strict';
const exe=resolve('src-tauri/target/release/minidaw.exe'),folder=resolve('tests/local/export',randomUUID());await mkdir(folder,{recursive:true});
const recent=join(process.env.APPDATA,'local.minidaw.desktop/recent-projects.json');let savedRecent;try{savedRecent=await readFile(recent);}catch{}
const report={checks:[],executableSha256:createHash('sha256').update(await readFile(exe)).digest('hex')};let child,browser,page,prefs;const errors=[],sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label,limit=45000){const at=performance.now();while(performance.now()-at<limit){if(await fn())return;await sleep(40);}throw Error(label);}
const invoke=(name,args={})=>page.evaluate(({name,args})=>window.__TAURI_INTERNALS__.invoke(name,args).catch(e=>{throw Error(JSON.stringify(e));}),{name,args});
const project=()=>invoke('project_snapshot'),audio=()=>invoke('engine_snapshot');
async function idle(){await until(async()=>!await page.locator('#project-save').isDisabled(),'Project idle');await sleep(180);}
async function edit(request){await invoke('edit_project',{revision:(await project()).revision,request});await idle();}
async function panel(id,open){const b=page.locator('#show-'+id);if((await b.getAttribute('aria-pressed')==='true')!==open)await b.click();await sleep(80);}
async function select(id){await page.evaluate(id=>document.dispatchEvent(new CustomEvent('select-clips',{detail:[id]})),id);await sleep(100);}
async function enter(id,value){const input=page.locator(id);await input.fill(String(value));await input.press('Enter');await idle();}
const clip=async id=>(await project()).document.tracks.flatMap(t=>t.clips).find(c=>c.clipId===id);
const length=c=>Number(c.sourceEnd)-Number(c.sourceStart),position=c=>Number(c.position.numerator)/c.position.denominator;
async function measure(){await sleep(1800);const a=await audio();await sleep(5000);const b=await audio();const n=b.metrics.callbacks-a.metrics.callbacks;return {callbackAvgMs:(b.metrics.callbackAvgMs*b.metrics.callbacks-a.metrics.callbackAvgMs*a.metrics.callbacks)/n,callbacks:n,overruns:b.metrics.overruns-a.metrics.overruns,deviceOverruns:b.metrics.deviceCallbackOverruns-a.metrics.deviceCallbackOverruns,starvation:b.source.starvation-a.source.starvation,streamErrors:b.streamErrors-a.streamErrors,source:b.source,peakDb:b.master.peakDb};}
try {
 child=spawn(exe,[],{env:{...process.env,WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:'--remote-debugging-port=19270'},stdio:'ignore',windowsHide:true});
 await until(async()=>{try{browser=await chromium.connectOverCDP('http://127.0.0.1:19270');return true;}catch{return false;}},'Release CDP');
 await until(async()=>{page=browser.contexts()[0].pages().find(p=>p.url().includes('tauri.localhost'));return !!page;},'Release page');page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1440,height:960});await idle();
 prefs=await page.evaluate(()=>Object.fromEntries(['minidaw.ui.panels.v1','minidaw.ui.fontScale','minidaw.ui.spectrum.v1','minidaw.ui.snap','minidaw.ui.grid','minidaw.ui.rulerFormat'].map(k=>[k,localStorage.getItem(k)])));
 for(const[id,show]of [['arrangement',true],['media',false],['performance',false],['spectrum',false],['piano',false],['mixer',false]])await panel(id,show);
 const openExport=async()=>{await page.locator('#file-menu > summary').click();await page.locator('#audio-export').click();await until(async()=>await page.locator('#export-rate').textContent()!=='','Rate');};
 const runExport=async(path,format)=>{await page.locator('#export-path').fill(path);await page.locator('#export-format').selectOption(format);await page.locator('#export-start').click();await until(async()=>/완료 ·|같은 이름|원본|취소했습니다|완료하지 못/.test(await page.locator('#export-message').textContent()),'Export completed',120000);return invoke('export_status');};
 const closeExport=async()=>{await until(async()=>await page.locator('#export-cancel').textContent()==='닫기','Export not running');await page.locator('#export-cancel').click();};
 const assertWave=async(path,bits,frames)=>{const b=await readFile(path);assert.equal(b.toString('ascii',0,4),'RIFF');assert.equal(b.readUInt32LE(4)+8,b.length);assert.equal(b.readUInt16LE(20),bits===32?3:1);assert.equal(b.readUInt16LE(22),2);assert.equal(b.readUInt32LE(24),48000);assert.equal(b.readUInt16LE(34),bits);let at=36;while(b.toString('ascii',at,at+4)!=='data')at+=8+b.readUInt32LE(at+4);const data=b.subarray(at+8);assert.equal(data.length,frames*2*bits/8);return data;};
 await invoke('new_project',{revision:(await project()).revision,discard:true});await idle();
 const resident=resolve('tests/fixtures/stereo-44100.wav'),long=resolve('tests/generated/long-400s-48000-2ch.wav');const originalHash=createHash('sha256').update(await readFile(resident)).digest('hex');
 await invoke('load_audio',{path:resident,trackId:null});await idle();const ta=(await project()).document.tracks[0].trackId,ca=(await project()).document.tracks[0].clips[0].clipId;
 await edit({command:'audio.trim',clipIds:[ca],sourceStart:'441',sourceEnd:'176841'});await edit({command:'audio.stretch',clipIds:[ca],stretchFrames:'211680'});await edit({command:'audio.pitch',clipIds:[ca],pitchShift:{semitones:2,cents:31}});await edit({command:'audio.fade',clipIds:[ca],fadeIn:'8000',fadeOut:'10000',curve:'cosine'});await edit({command:'track.mix',trackIds:[ta],volumeDb:-12,pan:-.3});
 await edit({command:'track.add',trackKind:'audio'});const tb=(await project()).document.tracks.at(-1).trackId;await invoke('load_audio',{path:long,trackId:tb});await idle();const cb=(await project()).document.tracks.at(-1).clips[0].clipId;await edit({command:'audio.trim',clipIds:[cb],sourceStart:'0',sourceEnd:'1440000'});await edit({command:'audio.tempoSync',clipIds:[cb],tempoSync:true,sourceBpm:120});await edit({command:'project.tempo',bpm:137.47});await edit({command:'track.mix',trackIds:[tb],volumeDb:-12,pan:.2});
 await edit({command:'midi.track.add'});const tm=(await project()).document.tracks.at(-1).trackId;await edit({command:'midi.track.instrument',trackIds:[tm],instrument:'basicSynth'});await edit({command:'midi.clip.add',trackIds:[tm],targetTick:'0',lengthTick:'57600000'});const cm=(await project()).document.tracks.at(-1).clips[0].clipId;await edit({command:'midi.note.add',clipIds:[cm],targetTick:'12345',lengthTick:'57587655',pitch:60,velocity:74});await edit({command:'track.mix',trackIds:[tm],volumeDb:-15,pan:.35});
 for(const[track,kind]of [[ta,'eq'],[tb,'compressor'],[tm,'reverb'],[tm,'delay'],['master','limiter']])await edit({command:'effect.add',trackIds:track==='master'?[]:[track],effectKind:kind});
 await edit({command:'master.volume',volumeDb:-3});
 for(const[track,param,values]of [[ta,'volumeDb',[[0,-12],[57600000,-18]]],[tb,'pan',[[0,-.2],[57600000,.4]]],[tm,'synth.levelDb',[[0,-3],[57600000,-9]]],['master','volumeDb',[[0,-3],[57600000,-6]]]]){await edit({command:'automation.lane.add',trackIds:[track],parameter:{name:param}});const lane=(await project()).document.automation.find(a=>a.trackId===track).lanes.at(-1).laneId;for(const[tick,value]of values)await edit({command:'automation.point.set',trackIds:[track],laneId:lane,parameter:{name:param},targetTick:String(tick),value});}
 await edit({command:'project.cycle',cycle:{enabled:true,startTick:'0',endTick:'3840000'}});const before=await project();await page.locator('#zoom-fit').click();
 await invoke('transport_command',{action:'play'});await sleep(1800);const baseline=await audio();await openExport();report.exports=[];
 for(const[format,bits]of [['pcm16',16],['pcm24',24],['float32',32]]){const path=join(folder,format+'.wav');const s=await runExport(path,format);assert.equal(s.stage,'completed',JSON.stringify(s.error));report.exports.push(s.report);assert.equal(s.report.sampleRate,48000);assert.ok(s.report.seconds>26);assert.ok(s.report.realtimeFactor>1);assert.equal(s.report.clippedSamples,0);await assertWave(path,bits,s.report.frames);}
 const firstFloat=report.exports.at(-1),repeated=await runExport(join(folder,'repeated.wav'),'float32');assert.equal(repeated.stage,'completed');assert.deepEqual(await readFile(firstFloat.path),await readFile(repeated.report.path));
 const after=await audio();report.concurrentPlayback={backend:after.output.backend,callbacks:after.metrics.callbacks-baseline.metrics.callbacks,callbackAvgMs:(after.metrics.callbackAvgMs*after.metrics.callbacks-baseline.metrics.callbackAvgMs*baseline.metrics.callbacks)/(after.metrics.callbacks-baseline.metrics.callbacks),overruns:after.metrics.overruns-baseline.metrics.overruns,deviceOverruns:after.metrics.deviceCallbackOverruns-baseline.metrics.deviceCallbackOverruns,starvation:after.source.starvation,streamErrors:after.streamErrors-baseline.streamErrors,cyclePass:after.transport.cyclePass};assert.equal(after.transport.state,'playing');assert.equal(report.concurrentPlayback.backend,'ASIO');assert.equal(report.concurrentPlayback.overruns,0);assert.equal(report.concurrentPlayback.deviceOverruns,0);assert.equal(report.concurrentPlayback.starvation,0);assert.equal(report.concurrentPlayback.streamErrors,0);
 const now=await project();assert.equal(now.revision,before.revision);assert.deepEqual(now.document,before.document);assert.deepEqual(now.history,before.history);report.checks.push('Native Export dialog produces all WAV formats at 48 kHz: resident + long Streaming Audio, Stretch/Pitch/Tempo Sync, MIDI Synth, Track/Master Inserts and Automation; full duration despite enabled Cycle.');
 // Quantization must match the same Master, without dither/normalization.
 const f=await assertWave(firstFloat.path,32,firstFloat.frames),pcm16=await assertWave(report.exports[0].path,16,firstFloat.frames),pcm24=await assertWave(report.exports[1].path,24,firstFloat.frames);let e16=0,e24=0;
 for(let i=0;i<f.length/4;i++){const x=f.readFloatLE(i*4);const a=Math.round(Math.min(32767,Math.max(-32768,x*32768)));const b=Math.round(Math.min(8388607,Math.max(-8388608,x*8388608)));e16=Math.max(e16,Math.abs(a-pcm16.readInt16LE(i*2)));e24=Math.max(e24,Math.abs(b-pcm24.readIntLE(i*3,3)));}assert.ok(e16<=1&&e24<=1);report.quantizationMaxIntegerDelta={pcm16:e16,pcm24:e24};
 report.checks.push('Repeat Float32 WAV is byte-identical. PCM16/24 match quantization of the same float Master. Export leaves project revision/history/data unchanged.');
 await page.screenshot({path:'docs/validation/export-ui.png'});await closeExport();await invoke('transport_command',{action:'stop'});
 // Explicit overwrite; abort never truncates the previous file.
 await openExport();await runExport(firstFloat.path,'float32');assert.ok(await page.locator('#export-replace').isVisible());const keep=await readFile(firstFloat.path);await page.locator('#export-replace').click();await until(async()=>await page.locator('#export-cancel').textContent()==='취소','Rendering');await page.locator('#export-cancel').click();await until(async()=>await page.locator('#export-cancel').textContent()==='닫기','Cancelled',120000);assert.equal((await invoke('export_status')).stage,'cancelled');assert.deepEqual(await readFile(firstFloat.path),keep);
 await page.locator('#export-path').fill(resident);await page.locator('#export-start').click();await until(async()=>/원본 Audio/.test(await page.locator('#export-message').textContent()),'Source protection');assert.equal(createHash('sha256').update(await readFile(resident)).digest('hex'),originalHash);await closeExport();report.checks.push('Cancel preserves existing WAV; source-file overwrite rejected; original source hash unchanged.');
 // Actual Arrangement Range drag, then exact [start,end) Selection WAV.
 await page.locator('[data-command="tool.rangeSelection"]').first().click();
 if(await page.locator('#snap-toggle').getAttribute('aria-pressed')==='true')await page.locator('#snap-toggle').click();
 const area=await page.locator('#clip-layer').boundingBox();const y=area.y+35;
 await page.mouse.move(area.x+area.width*.16,y);await page.mouse.down();await page.mouse.move(area.x+area.width*.48,y,{steps:12});await page.mouse.up();
 const exportBefore=await project();await openExport();await page.locator('#export-mode').selectOption('selection');
 const bounds=(await page.locator('#export-boundaries').textContent()).match(/\[(\d+), (\d+)\)/);assert.ok(bounds,'Selection boundaries shown');const from=Number(bounds[1]),to=Number(bounds[2]);assert.ok(to>from&&from>0);
 report.selection=[];
 for(const[format,bits]of [['float32',32],['pcm16',16],['pcm24',24]]){const status=await runExport(join(folder,'selection-'+format+'.wav'),format);assert.equal(status.stage,'completed',JSON.stringify(status.error));const r=status.report;assert.equal(r.frames,to-from);assert.equal(r.files[0].startFrame,from);assert.equal(r.files[0].endFrame,to);const data=await assertWave(r.path,bits,to-from);if(bits===32)assert.deepEqual(data,f.subarray(from*8,to*8));report.selection.push(r);}
 await page.screenshot({path:'docs/validation/export-selection-ui.png'});
 await page.locator('#export-mode').selectOption('track');await page.locator('#export-range').selectOption('selection');const singles=[];
 for(const track of [ta,tb,tm]){await page.locator('#export-tracks input[value="'+track+'"]').check();const s=await runExport(join(folder,'single-'+track+'.wav'),'float32');assert.equal(s.stage,'completed',JSON.stringify(s.error));assert.equal(s.report.frames,to-from);singles.push(s.report);}
 await page.locator('#export-mode').selectOption('stems');for(const input of await page.locator('#export-tracks input').all())await input.check();
 const stem=await runExport(folder,'float32');assert.equal(stem.stage,'completed',JSON.stringify(stem.error));assert.equal(stem.report.files.length,3);report.stems=stem.report;
 for(let i=0;i<3;i++){const out=stem.report.files[i];assert.equal(out.frames,to-from);assert.equal(out.startFrame,from);assert.equal(out.endFrame,to);assert.deepEqual(await readFile(out.path),await readFile(singles[i].path));}
 const again=await runExport(folder,'float32');assert.equal(again.stage,'completed');assert.notEqual(again.report.path,stem.report.path);for(let i=0;i<3;i++)assert.deepEqual(await readFile(stem.report.files[i].path),await readFile(again.report.files[i].path));
 await page.locator('#export-range').selectOption('project');const wholeStems=await runExport(folder,'pcm24');assert.equal(wholeStems.stage,'completed');for(const out of wholeStems.report.files){assert.equal(out.startFrame,0);assert.equal(out.frames,wholeStems.report.frames);await assertWave(out.path,24,out.frames);}report.fullStems=wholeStems.report;
 await page.screenshot({path:'docs/validation/export-stems-ui.png'});await closeExport();
 const exportAfter=await project();assert.equal(exportAfter.revision,exportBefore.revision);assert.deepEqual(exportAfter.document,exportBefore.document);assert.deepEqual(exportAfter.history,exportBefore.history);
 report.checks.push('Mouse-dragged Arrangement Selection exports exact sample interval in all 3 WAV formats; Float32 equals the full Master slice. Three individual Audio/Streaming/MIDI exports match their Stem WAVs byte-for-byte; common start/end/length, full-project tails, collision-safe batch folders, unchanged project/history.');
 await invoke('transport_command',{action:'play'});await sleep(300);await invoke('transport_command',{action:'pause'});assert.equal((await audio()).transport.state,'paused');await invoke('transport_command',{action:'play'});await sleep(300);assert.equal((await audio()).transport.state,'playing');await invoke('transport_command',{action:'stop'});
 for(const scale of ['90','125','110']){await page.locator('#font-scale').selectOption(scale);await openExport();assert.ok(await page.locator('#export-dialog').evaluate(e=>{const b=e.getBoundingClientRect();return b.left>=0&&b.right<=innerWidth&&b.top>=0&&b.bottom<=innerHeight;}));await closeExport();}
 assert.deepEqual(errors,[]);assert.equal(await page.locator('#error').isVisible(),false);assert.equal((await readdir(folder)).some(n=>n.endsWith('.tmp')),false);report.passed=true;
}catch(e){report.error=String(e.stack??e);report.pageErrors=errors;process.exitCode=1;if(page){report.uiError=await page.locator('#error-text').textContent().catch(()=>null);report.exportMessage=await page.locator('#export-message').textContent().catch(()=>null);report.exportStatus=await invoke('export_status').catch(()=>null);report.lastAudio=await audio().catch(()=>null);await page.screenshot({path:'docs/validation/export-failure.png'}).catch(()=>{});}}
finally{
 if(page&&prefs)await page.evaluate(p=>{for(const[k,v]of Object.entries(p)){if(v===null)localStorage.removeItem(k);else localStorage.setItem(k,v);}},prefs).catch(()=>{});
 if(browser)await browser.close();if(child?.exitCode===null){const exited=once(child,'exit');child.kill();await exited;}
 if(child){report.remainingTempCaches=(await readdir(process.env.TEMP)).filter(n=>n.startsWith(`minidaw-stretch-${child.pid}-`));if(report.remainingTempCaches.length){report.passed=false;report.error='Temporary cache not removed on exit';process.exitCode=1;}}
 if(savedRecent)await writeFile(recent,savedRecent);else await unlink(recent).catch(()=>{});
 await writeFile('docs/validation/export-ui.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,error:report.error,exports:report.exports,playback:report.concurrentPlayback,checks:report.checks}));
}
