// Focused UI regression against the actual compiled app. No audio benchmarks.
import {chromium} from 'playwright-core';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {readFile,writeFile,mkdir,unlink} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import {resolve,join} from 'node:path';
import assert from 'node:assert/strict';
const exe=resolve('src-tauri/target/release/minidaw.exe'), folder=resolve('tests/local/ui-panels',randomUUID());
await mkdir(folder,{recursive:true});
const recent=join(process.env.APPDATA,'local.minidaw.desktop/recent-projects.json');
let savedRecent;try{savedRecent=await readFile(recent);}catch{}
const report={executableSha256:createHash('sha256').update(await readFile(exe)).digest('hex'),checks:[]};
let child,browser,page,prefs;const errors=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label,timeout=20000){const t=performance.now();while(performance.now()-t<timeout){if(await fn())return;await sleep(35);}throw Error(label);}
const invoke=(name,args={})=>page.evaluate(({name,args})=>window.__TAURI_INTERNALS__.invoke(name,args),{name,args});
const project=()=>invoke('project_snapshot'),snapshot=()=>invoke('engine_snapshot');
const clips=p=>p.document.tracks.flatMap(t=>t.clips);
async function idle(){await until(async()=>!(await page.locator('#project-save').isDisabled()),'Project idle');await sleep(100);}
async function key(k){await page.keyboard.press(k);await idle();}
async function toggle(id,open){const button=page.locator('#show-'+id);if((await button.getAttribute('aria-pressed')==='true')!==open)await button.click();await sleep(100);}
async function reveal(id){const p=await project();const track=p.document.tracks.find(t=>t.clips.some(c=>c.clipId===id));const header=page.locator(`.track-header[data-track-id="${track.trackId}"]`);await header.evaluate(el=>document.getElementById('track-scroll').scrollTop=el.offsetTop);await sleep(100);for(let i=0;i<20;i++){const node=page.locator(`.audio-clip[data-clip-id="${id}"]`);if(await node.count()){await node.scrollIntoViewIfNeeded();await sleep(80);return node;}await page.locator('#track-scroll').evaluate(el=>el.scrollTop+=100);await sleep(70);}throw Error('Clip not visible '+id);}
async function select(id){const node=await reveal(id),b=await node.boundingBox();await page.mouse.click(b.x+Math.min(45,b.width*.3),b.y+b.height*.65);return node;}
async function drag(id,handle,delta){const node=await reveal(id),target=handle?node.locator(`[data-handle="${handle}"]`):node,b=await target.boundingBox();const x=handle?b.x+b.width/2:b.x+Math.min(50,b.width*.3),y=handle?b.y+b.height*.6:b.y+b.height*.65;const before=await project(),s=await snapshot();await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+delta,y,{steps:30});assert.equal((await project()).revision,before.revision);assert.equal((await snapshot()).transport.appliedCommand,s.transport.appliedCommand);await page.mouse.up();await until(async()=>(await project()).revision===before.revision+1,'one edit commit');await idle();assert.equal((await project()).history.undo,before.history.undo+1);return await project();}
async function noOverlap(){const boxes=await page.locator('.audio-clip').evaluateAll(nodes=>nodes.map(n=>({id:n.dataset.clipId,track:n.dataset.trackId,lane:n.dataset.lane,x:n.offsetLeft,y:n.offsetTop,w:n.offsetWidth,h:n.offsetHeight})));for(let a=0;a<boxes.length;a++)for(let b=a+1;b<boxes.length;b++){const x=boxes[a],y=boxes[b];assert.ok(x.x+x.w<=y.x+2||y.x+y.w<=x.x+2||x.y+x.h<=y.y||y.y+y.h<=x.y,`Covered clips ${x.id}/${y.id}`);}return boxes;}
try{
 child=spawn(exe,[],{env:{...process.env,WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:'--remote-debugging-port=19236'},stdio:'ignore',windowsHide:true});
 await until(async()=>{try{browser=await chromium.connectOverCDP('http://127.0.0.1:19236');return true;}catch{return false;}},'Release CDP');
 await until(async()=>{page=browser.contexts()[0].pages().find(p=>p.url().includes('tauri.localhost'));return !!page;},'Release page');
 page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1440,height:960});await idle();
 prefs=await page.evaluate(()=>({panels:localStorage.getItem('minidaw.ui.panels.v1'),font:localStorage.getItem('minidaw.ui.fontScale')}));
 await toggle('arrangement',true);await toggle('media',true);await toggle('performance',false);
 await invoke('load_audio',{path:resolve('tests/fixtures/stereo-44100.wav')});await until(async()=>await page.locator('.audio-clip').count()===1,'Imported clip');await idle();
 let p=await project();await select(clips(p)[0].clipId);await key('Control+c');for(let i=0;i<6;i++)await key('Control+v');p=await project();assert.equal(clips(p).length,7);
 const track=p.document.tracks[0];assert.equal(new Set(clips(p).map(c=>JSON.stringify(c.position))).size,1,'same original overlap policy');
 report.overlap=[];for(const clip of clips(p)){await reveal(clip.clipId);const b=await noOverlap();report.overlap.push(b);assert.ok(b.some(n=>n.id===clip.clipId));}
 assert.equal(await page.locator('.track-header').count(),1);report.checks.push('Seven fully overlapping events each have an independent visible/editable lane in their original Track. No project reordering or overlap policy change.');
 await select(clips(p)[0].clipId);await page.keyboard.down('Control');await select(clips(p)[1].clipId);await page.keyboard.up('Control');await key('x');assert.ok(clips(await project()).some(c=>Number(c.fadeIn.sourceFrames)>0));
 await page.locator('.file-menu summary').filter({hasText:'오디오'}).click();await page.locator('#audio-menu-items [data-command="audio.normalize"]').click();await page.locator('#normalize-target').fill('-1');await page.locator('#normalize-apply').click();await idle();assert.ok(clips(await project()).some(c=>c.gain>1));await key('Control+z');await key('Control+z');report.checks.push('Crossfade and Peak Normalize menu/dialog retain real command connections; Undo restores both.');
 await page.locator('#track-scroll').evaluate(el=>el.scrollTop=0);await sleep(100);
 const body=await page.locator('#clip-layer').boundingBox();await page.mouse.move(body.x+100,Math.max(body.y+50,350));const top=await page.locator('#track-scroll').evaluate(el=>el.scrollTop);await page.mouse.wheel(0,300);await until(async()=>(await page.locator('#track-scroll').evaluate(el=>el.scrollTop))>top,'Ordinary vertical wheel');
 const ruler=await page.locator('#waveform').boundingBox(),engineBefore=await snapshot();await page.mouse.move(ruler.x+ruler.width*.45,ruler.y+12);await page.keyboard.down('Control');await page.mouse.wheel(0,-220);await page.keyboard.up('Control');await sleep(200);assert.notEqual(await page.locator('#zoom-value').textContent(),'1.0×');
 const extent=Math.max(10,engineBefore.duration*1.25),span=extent-Number(await page.locator('#scroll').getAttribute('max'));assert.ok(Math.abs(Number(await page.locator('#scroll').inputValue())+.45*span-.45*extent)<.025,'Cursor centered wheel anchor');
 await page.keyboard.down('Shift');await page.mouse.wheel(0,180);await page.keyboard.up('Shift');await sleep(180);assert.ok(Number(await page.locator('#scroll').inputValue())>0);assert.equal((await snapshot()).transport.appliedCommand,engineBefore.transport.appliedCommand);
 await page.mouse.move(ruler.x+ruler.width*.3,ruler.y+12);await page.mouse.down();await page.mouse.move(ruler.x+ruler.width*.55,ruler.y+12,{steps:100});assert.equal((await snapshot()).transport.appliedCommand,engineBefore.transport.appliedCommand);await page.mouse.up();await until(async()=>(await snapshot()).transport.appliedCommand===engineBefore.transport.appliedCommand+1,'Ruler commit');
 await page.locator('#zoom-fit').click();report.checks.push('Normal wheel scrolls Tracks; Ctrl wheel zoom and Shift wheel pan; ruler 100 moves produce 0 seek, pointerup exactly 1.');
 await toggle('media',false);await page.locator('#track-scroll').evaluate(el=>el.scrollTop=0);await sleep(150);
 const id=clips(await project())[0].clipId;await select(id);const beforeMove=structuredClone((await project()).document);await drag(id,null,25);const moved=structuredClone((await project()).document);assert.notDeepEqual(moved,beforeMove);await key('Control+z');assert.deepEqual((await project()).document,beforeMove);await key('Control+Shift+z');assert.deepEqual((await project()).document,moved);
 await drag(id,'trim-left',15);await drag(id,'trim-right',-15);await drag(id,'fade-in',20);await drag(id,'fade-out',-20);
 const n=clips(await project()).length;await key('3');const node=await reveal(id),box=await node.boundingBox();await page.mouse.click(box.x+box.width*.5,box.y+box.height*.6);await idle();assert.equal(clips(await project()).length,n+1);await key('Control+z');assert.equal(clips(await project()).length,n);await key('1');
 report.checks.push('Real mouse Move, both Trim edges, Fade handles, Split, exact Undo/Redo; drag previews produce no project/transport commands until release.');
 await select(id);await key('Shift+m');assert.ok(clips(await project()).find(c=>c.clipId===id).mute);await key('Shift+u');await page.locator('#clip-gain').fill('-3');await page.locator('#clip-gain').press('Tab');await idle();assert.ok(clips(await project()).find(c=>c.clipId===id).gain<1);await select(id);await key('Control+d');await key('Control+x');await key('Control+v');await key('Delete');await key('Control+z');
 await key('2');const first=await reveal(id),rb=await first.boundingBox();await page.mouse.move(rb.x+20,rb.y+50);await page.mouse.down();await page.mouse.move(rb.x+60,rb.y+50,{steps:20});await page.mouse.up();assert.equal(await page.locator('#edit-range').isVisible(),true);await key('Shift+x');await key('Delete');await key('Control+z');await key('1');
 report.checks.push('Existing Mute/Unmute/Gain/Duplicate/Cut/Copy/Paste/Delete and Range Split/Delete remain connected to real project commands.');
 const a=await page.locator('#panel-arrangement').boundingBox();await toggle('performance',true);const withPerf=await page.locator('#panel-arrangement').boundingBox();assert.ok(withPerf.width<a.width-150);await page.locator('#panel-performance [data-panel-close]').click();await sleep(120);const restored=await page.locator('#panel-arrangement').boundingBox();assert.ok(Math.abs(restored.width-a.width)<2);assert.equal(await page.locator('.panel-divider:visible').count(),0);
 await toggle('performance',true);const sep=page.locator('.panel-divider'),sb=await sep.boundingBox();const perfBefore=await page.locator('#panel-performance').boundingBox();await page.mouse.move(sb.x+3,sb.y+100);await page.mouse.down();await page.mouse.move(sb.x-90,sb.y+100,{steps:20});await page.mouse.up();await sleep(120);const perfAfter=await page.locator('#panel-performance').boundingBox();assert.ok(perfAfter.width>perfBefore.width+60);
 await toggle('media',true);const mediaBefore=await page.locator('#panel-media').boundingBox(),ms=await page.locator('.panel-divider').first().boundingBox();await page.mouse.move(ms.x+3,ms.y+80);await page.mouse.down();await page.mouse.move(ms.x+55,ms.y+80,{steps:20});await page.mouse.up();await sleep(150);assert.ok((await page.locator('#panel-media').boundingBox()).width>mediaBefore.width+30);
 await toggle('arrangement',false);assert.equal(await page.locator('#panel-arrangement').isVisible(),false);await toggle('media',false);await toggle('performance',false);assert.equal(await page.locator('#workspace-empty').isVisible(),true);await toggle('arrangement',true);await toggle('media',true);await toggle('performance',true);
 report.checks.push('Every panel opens/closes; close returns all space and removes separators; Arrangement, Media and Performance resize through common captured splitters; all-closed state reopens.');
 report.layouts=[];for(const size of [{width:1440,height:960},{width:960,height:720},{width:760,height:520}]){await page.setViewportSize(size);for(const font of ['90','110','125']){await page.locator('#font-scale').selectOption(font);await sleep(160);const layout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,panels:[...document.querySelectorAll('.workspace-panel:not([hidden])')].map(el=>({id:el.id,w:el.clientWidth,h:el.clientHeight,scroll:el.scrollWidth})),ruler:document.getElementById('waveform').clientWidth}));assert.equal(layout.overflow,false);assert.ok(layout.ruler>50);for(const p of layout.panels)assert.ok(p.scroll<=p.w+2,`${p.id} overflow ${p.scroll}/${p.w}`);report.layouts.push({size,font,...layout});}}
 await page.setViewportSize({width:1440,height:960});await page.locator('#font-scale').selectOption('110');await toggle('performance',false);await page.locator('#zoom-fit').click();
 // Existing schema: UI displays arbitrary Track IDs/names; only one populated Track is required by the unchanged audio engine.
 p=await project();const multi=structuredClone(p.document),template=multi.tracks[0];multi.projectId=randomUUID();multi.name='Track layout';multi.tracks=Array.from({length:7},(_,i)=>({...structuredClone(template),trackId:randomUUID(),name:['Guitar','Room','Music Events','Voice','Ambience','Guide','Outro'][i],clips:i===2?template.clips:[]}));const path=join(folder,'tracks.minidaw');await writeFile(path,JSON.stringify(multi));await invoke('open_project',{path,revision:p.revision,discard:true});await idle();assert.equal(await page.locator('.track-header').count(),7);const third=multi.tracks[2];await page.locator(`.track-header[data-track-id="${third.trackId}"]`).evaluate(el=>document.getElementById('track-scroll').scrollTop=el.offsetTop);await sleep(150);await noOverlap();assert.ok(await page.locator(`.audio-clip[data-track-id="${third.trackId}"]`).count()>0);await select(third.clips[0].clipId);await drag(third.clips[0].clipId,null,15);await key('Control+z');
 await page.screenshot({path:'docs/validation/ui-panels.png'});
 const visibleTracks=structuredClone((await project()).document);visibleTracks.tracks[0].clips=visibleTracks.tracks[2].clips.splice(0,2);const displayPath=join(folder,'multiple-populated-tracks.minidaw');await writeFile(displayPath,JSON.stringify(visibleTracks));await invoke('open_project',{path:displayPath,revision:(await project()).revision,discard:true});await idle();await page.locator('#track-scroll').evaluate(el=>el.scrollTop=0);await sleep(150);assert.ok(await page.locator(`.audio-clip[data-track-id="${visibleTracks.tracks[0].trackId}"]`).count()>0);await noOverlap();await page.screenshot({path:'docs/validation/ui-panels-tracks.png'});
 report.checks.push('Seven document Track rows with real names/IDs, synchronized Track/Event vertical scroll; edits target clips on the third Track (not hardcoded Audio 1). Window resize and 90/110/125% font layouts pass.');
 // Reload the WebView to verify UI preferences without changing the document.
 const beforeReload=await page.evaluate(()=>localStorage.getItem('minidaw.ui.panels.v1'));await page.reload();await idle();assert.equal(await page.locator('#show-performance').getAttribute('aria-pressed'),'false');assert.equal(await page.evaluate(()=>localStorage.getItem('minidaw.ui.panels.v1')),beforeReload);report.checks.push('Panel visibility/sizes are independent UI preferences and survive WebView reload. Multiple populated Tracks display in separate rows; existing single-track playback restriction remains unchanged.');
 const rustBefore=JSON.parse(await readFile('tests/local/ui-panels/audio-source-before.json','utf8'));for(const [file,hash]of Object.entries(rustBefore))assert.equal(createHash('sha256').update(await readFile(join('src-tauri/src',file))).digest('hex'),hash);report.rustSourceFilesUnchanged=Object.keys(rustBefore).length;
 assert.deepEqual(errors,[]);report.passed=true;
}catch(e){report.error=String(e.stack??e);process.exitCode=1;if(page){await page.screenshot({path:'docs/validation/ui-panels-failure.png'}).catch(()=>{});report.lastProject=await project().catch(()=>null);report.lastSnapshot=await snapshot().catch(()=>null);}}
finally{if(page&&prefs)await page.evaluate(p=>{for(const [k,v]of [['minidaw.ui.panels.v1',p.panels],['minidaw.ui.fontScale',p.font]]){if(v===null)localStorage.removeItem(k);else localStorage.setItem(k,v);}},prefs).catch(()=>{});if(browser)await browser.close();if(child?.exitCode===null){const exit=once(child,'exit');child.kill();await exit;}if(savedRecent)await writeFile(recent,savedRecent);else await unlink(recent).catch(()=>{});await writeFile('docs/validation/ui-panels.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,error:report.error,checks:report.checks}));}
